/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game_SignIn;

import Game_Menu.Menu;
import Game_Register.Register;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class SignIn extends javax.swing.JFrame {

    public static String text = " ";
    public static String password = " ";
    public static boolean logged;
    public static Connection dbConn;
    private int co;
    private String name,passwd;
    
    public SignIn() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignIn = new javax.swing.JButton();
        pwd = new javax.swing.JPasswordField();
        uName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        SignIn.setBackground(new java.awt.Color(0, 0, 0));
        SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LoginButton.png"))); // NOI18N
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn);
        SignIn.setBounds(190, 380, 150, 40);

        pwd.setBackground(new java.awt.Color(5, 23, 33));
        pwd.setForeground(new java.awt.Color(255, 255, 255));
        pwd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 130, 177), 3, true));
        pwd.setCaretColor(new java.awt.Color(0, 255, 255));
        pwd.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(pwd);
        pwd.setBounds(70, 340, 270, 30);

        uName.setBackground(new java.awt.Color(5, 23, 33));
        uName.setForeground(new java.awt.Color(255, 255, 255));
        uName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 130, 177), 3, true));
        uName.setCaretColor(new java.awt.Color(0, 255, 255));
        getContentPane().add(uName);
        uName.setBounds(70, 290, 270, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/regButton.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SignIn1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            dbConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/skyforce?zeroDateTimeBehavior=convertToNull", "root", "");
            ResultSet query = dbConn.createStatement().executeQuery("SELECT username,countvisited,password FROM user WHERE username = '" +uName.getText()+ "' AND password = '" +pwd.getText()+ "'");
            
            while(query.next()) {
                name=query.getString("username");
                passwd=query.getString("password");
                co = query.getInt("countvisited");
            }
           
            
            if(query.last() && name.equals(uName.getText()) && passwd.equals(pwd.getText()) ){
                
                co = co + 1;
                dbConn.prepareStatement("UPDATE user SET countvisited = '"+co+"' WHERE username = '"+uName.getText()+"'").executeUpdate();
                
                this.setVisible(false);
                new Menu(uName.getText()).setVisible(true);
                
            }
            else
            {
                 JOptionPane.showMessageDialog(uName,"Username or Password INCORRECT","Error",JOptionPane.OK_OPTION);
            }
        }
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //this.setVisible(false);
        //new Menu("Ranmal").setVisible(true);
        
    }//GEN-LAST:event_SignInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
}
